### PR TITLE
Documentation for migration design

### PR DESCRIPTION
**Pull request by alexandraorth**

### CODE REVIEW

**Comment by haikalpribadi** [comment]
I'll merge this @alexandraorth but it seems like you also committed an empty file? -> mindmaps-migration/design/json-examples/example.gqlm

**Comment by haikalpribadi** [comment]
@bolerio lets review this design for migration templating engine

**Comment by alexandraorth** [comment]
@haikalpribadi yes, that empty file is one of the ones that I will flesh out with more examples today

**Comment by bolerio** [comment]
@alexandraorth  @haikalpribadi Where can I look at it to review?

**Comment by alexandraorth** [comment]
@bolerio it's the readme file in this pull request: 
https://github.com/mindmapsdb/mindmapsdb/tree/master/mindmaps-migration/design

**Pull request merged**
