### PR TITLE
Refactor mindmaps-test to use maven profiles

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Pull request merged**
