### PR TITLE
Improve error messages when something has no variable name or ID

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by bolerio** [comment]
Closing this one too because of test failure and also the previous PR is flagged with merge conflicts with latest codebase. So new PR with tests passing is in order :)

**Comment by aelred** [comment]
Reopening because it's rebased and passing locally now.

**Pull request closed without merging**
