### PR TITLE
Move Graql tests into mm-test, to allow removal of mm-graph dependency

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
please retest this please

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by fppt** [comment]
@aelred I am very interested in seeing this go in. Could you rebase please 😃 ?

**Comment by aelred** [comment]
@fppt There are so many conflicts, I'm going to totally re-do it from scratch today.

**Comment by fppt** [comment]
@aelred Well that is unfortunate. Tell me if there is anything I can do to help with this one.

**Comment by aelred** [comment]
I'm closing this one. There's a new PR open that does the same thing without all the conflicts!

**Pull request closed without merging**
